# Clod-MC config

homes:
  # maximum amount of homes across all worlds
  max-allowed: 2
  # name of the world that /spawn takes you to
  overworld-name: world

afk:
  # time in seconds before an idle player is marked as afk
  idle-time: 300

mailer:
  # send admin emails here (eg. notifications of invites)
  admin-addr: clod@glob.au
  # smtp server hostname
  hostname: in1-smtp.messagingengine.com
  # email sender's name
  sender-name: Clod Minecraft Server
  # email sender's address
  sender-addr: clod@glob.au

invite:
  # minimum playtime in minutes before a player can /invite
  playtime: 240

required-plugins:
  # list of plugins that must be loaded.  if any of these
  # are not running, players will not be able to join
  - GriefPrevention

# circular world borders
border:
  world:
    x: 158.5
    z: 2.5
    radius: 7500
  world_nether:
    x: 6.5
    z: 0.5
    radius: 7500
