name: ClodMC
version: '${version}'
main: au.com.glob.clodmc.ClodMC
bootstrapper: au.com.glob.clodmc.modules.ModuleRegistry
api-version: '1.21.7'
authors: [ glob ]
dependencies:
  bootstrap:
    GriefPrevention:
      load: BEFORE
      required: false
  server:
    GriefPrevention:
      load: BEFORE
      required: false
    BlueMap:
      load: BEFORE
      required: false
    Geyser-Spigot:
      load: BEFORE
      required: false
