name: close pull request
on:
  pull_request_target:
    types: [opened, reopened]
permissions:
  pull-requests: write
  issues: write
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: "README.md"
          sparse-checkout-cone-mode: false
      - name: close
        env:
          GH_TOKEN: ${{ github.token }}
          PR: ${{ github.event.number }}
        run: |
          gh pr close ${{ env.PR }} --comment "(Automated Close) This repository does not accept pull requests"
          gh pr lock ${{ env.PR }}
