name: test
on: push
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: jdk
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
        with:
          distribution: microsoft
          java-version: 25

      - name: setup gradlew
        run: ./gradlew --version

      - name: setup python
        run: pip install --disable-pip-version-check --upgrade uv

      - name: test
        run: make test
