name: test
on: push
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: jdk
        uses: actions/setup-java@v5
        with:
          distribution: microsoft
          java-version: 25

      - name: setup gradlew
        run: ./gradlew --version

      - name: setup python
        run: pip install --disable-pip-version-check --upgrade uv

      - name: test
        run: make test
