name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install utils
        run: |
          apt update
          apt install --yes curl
          curl -LsSf https://astral.sh/uv/install.sh | XDG_BIN_HOME=/usr/local/bin sh
          uvx ruff version

      - name: jdk
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: 21

      - name: verify gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: setup gradlew
        run: ./gradlew --version

      - name: test
        run: make test
